### ISSUE TITLE
Hashtag for NSFW content.

### ISSUE THREAD

**Issue by Antiarchitect** [zhukov/webogram#1145]
It would be nice to hide all media content and show it only on-demand if the message contains a specific tag i.e. #nsfw. If you do not want to frame your colleagues it is a must have feature.

**Comment by johnjrmurray** [comment]
maybe the ability to collapse all media would be better, like slack does?

**Comment by mk-pmb** [comment]
In order to support more languages and more reasons, let's allow users to configure a list of hash tags, each with a ugliness danger score as a number (positive or negative), and an ugliness danger limit number. For all hashtags in the message that are also on the list, sum the scores, compare to limit, and if the limit is reached, set initial display state to collapsed.
