### ISSUE TITLE
Button "edit" in top panel not working

### ISSUE THREAD

**Issue by alexdeg** [zhukov/webogram#1258]
This button don't open window for edit user information

**Comment by Akronix** [comment]
It does for me, which browser are you using? does the console say something??

**Comment by alexdeg** [comment]
Ubuntu, chrome 54.0.2840.59 (64-bit)
Console empty
http://pastenow.ru/15K43 
After clicking on button showing this panel instead a message textbox

**Comment by Akronix** [comment]
hi @alexdeg !
I'm testing it on Ubuntu 16.04 and Chrome 54.0.2840.71 and going to settings > Edit, displays the `Edit profile` modal dialog correctly.
Are you sure you're using webogram from the official domain (https://web.telegram.org)?
Maybe you can post a video / gif showing your process since I'm unable to reproduce your issue.

**Comment by alexdeg** [comment]
https://www.youtube.com/watch?v=sgsGFIHwWqs&feature=youtu.be

**Comment by Akronix** [comment]
Oh I thought you were talking about another "Edit" button...

Well, I have followed your steps in different browsers and systems and It looks like what you're experiencing is the expected behaviour. It changes the "standard" mode to an "edit" mode to just select messages and do something with them. But using that word for two different things it's definitely confusing.

We should change that word by another more close to what it does...or remove directly remove as I don't find it very useful?. Maybe some user-cases such touchable screens can find it useful; so I would like to hear some feedback from different users, in order to know if they use or how they use that "Edit" button.

**Comment by zhukov** [comment]
You should select some messages in order to activate "delete" and "forward" buttons.
