### ISSUE TITLE
layer what?

### ISSUE THREAD

**Issue by mbande** [zhukov/webogram#1320]
it [seems](https://github.com/zhukov/webogram/blob/master/app/js/lib/config.js#L104) that the master branch is on level 57,
in telegram website, the most recent [documented](https://core.telegram.org/api/layers#layer-18) layer is 18
what is going on here? how one could find out what each layer specification is? whats is the new features included, etc.

**Comment by zhukov** [comment]
I'm sorry, but that's the question for Telegram / API, not for Web application. Use Settings - Ask a question.

**Comment by stek29** [comment]
@mbande have a look at https://tjhorner.com/tl-schema

**Comment by nuclight** [comment]
@zhukov Tried to "Settings - Ask a question" and for 9 days stil got no reply. 

@stek29 looked there, and many links are 404. Any _real_ docs?

**Comment by stek29** [comment]
@nuclight `Vector<Foo>` is 404 even if `Foo` isn't. Also, that site is unofficial and just gives a quick reference, latest schema in TL can be found in TDesktop repo, and in JSON -- here.

Also, Telegram Support is ran by volunteers, keep that in mind. Twitter is better, but it may ignore your questions too. You can also try to contact via https://telegram.org/support.

About the _real_ docs -- no, there are no _publicly available_, updated and _real_ documentation.

**Comment by nuclight** [comment]
@stek29 so where do _you_ (@zhukov and other official apps' developers) get more descriptive docs about fresh layer than just a schema.tl itself? And more importantly, _why_ it is **not** publicly available?

The demand for API docs is real, which is not - and _cannot be_ - covered by existence of official apps / library. Think of at least telegram.link and telegram-cli (yes, how do you automate without it?) going unmaintained for more than a year.

At last, if no complete docs, still where could be API developers asked questions for most tangled / ununderstood moments on API ? Agree even if it is available only in Russian :)

**Comment by stek29** [comment]
@nuclight I am **not** official developer, I'm just an enthusiast, and I can't say for sure there is private documentation, because I just don't have any proofs of it's existence, but there's likely one.

You can try to ask official app devs (not a good idea sometimes), you can ask unofficial app devs (QtGram aka LibQTelegram, Cutegram, Android Contest participants, that UWP app -- real apps, not just forks with a bit of UI customizations like tabs or themes), and you can ask in some Telegram development related groups -- [@botoid](https://t.me/botoid) is the closest one I know (in Russian).

That's what I usually do, in addition to just using my mind to guess, test and read sources.

**Comment by munrocket** [comment]
Here all schemes 01-74 https://github.com/stek29/tl-schema
