### ISSUE TITLE
Double click to scroll to bottom of conversation

### ISSUE THREAD

**Issue by fqdb** [zhukov/webogram#1335]
In the native Telegram Desktop app, double clicking on the contact/group/channel in the left pane scrolls the chat window to the latest message. As far as I know there's no way to do this in Telegram Web, so it would be nice if this function can be implemented.

**Comment by whipermr5** [comment]
After looking through the code, it seems there is already functionality for this (albeit triggered by a single click instead of double click) [here](https://github.com/zhukov/webogram/blob/1a93895d4c1dc26cbbc2ad57e6606e041da5248e/app/js/controllers.js#L463), however it's not being triggered because `peerData.messageID` in [this](https://github.com/zhukov/webogram/blob/1a93895d4c1dc26cbbc2ad57e6606e041da5248e/app/js/controllers.js#L458) condition is unpopulated.

This is due to the `messageID` param only being set in `dialogSelect` if its value is true ([here](https://github.com/zhukov/webogram/blob/1a93895d4c1dc26cbbc2ad57e6606e041da5248e/app/js/controllers.js#L589)). Indeed, after modifying the code like so, single clicking on the contact/group/channel in the left pane does scroll the chat window to the latest message:
<img width="543" alt="screen shot 2017-02-21 at 6 32 32 pm" src="https://cloud.githubusercontent.com/assets/6811428/23161278/7fecad14-f864-11e6-9ddf-2720f003e3d9.png">

@zhukov can confirm whether this is a bug? If it is I'd gladly submit a PR :)

**Comment by zhukov** [comment]
@whipermr5 No I don't think this will fix the issue. Since messageID field will be empty anyway.

**Comment by whipermr5** [comment]
[This](https://github.com/zhukov/webogram/blob/1a93895d4c1dc26cbbc2ad57e6606e041da5248e/app/js/controllers.js#L458) condition is failing because messageID is empty, when it should be true or false. I tested my changes and the chat window indeed scrolls as expected.

**Comment by whipermr5** [comment]
@zhukov Was the scroll to bottom by single click on already selected chat an intended feature or a side effect of the search mechanism?

**Comment by zhukov** [comment]
that's a side effect for sure. can you provider a PR? will try it out.
