### ISSUE TITLE
Edit details other than name

### ISSUE THREAD

**Issue by llyrran** [zhukov/webogram#1523]
I am trying to delete my telephone number from my Telegram profile as I have started to receive spam txt messages. I can only edit my name and deleting my telephone number does not seem to be an option. I want my phone number off my profile to keep it private. I did not realize that my number would be emblazoned for any one to see other wise I would not have entered it. Thnaks

**Comment by stek29** [comment]
Your phone number is hidden from other users. They can only see it in the following three cases:
- If they already have your phone number saved in their address book.
- If you've shared your number yourself (with 'Share My Contact Info')
- If you have their phone number saved in your address book and you message them (as if they get your SMS).

They won't see your number otherwise — for instance, if they find you via our global search or in a group chat.

Also, there's no way to delete your phone number and there likely will never be, at least until TG allows accounts with no phone number. Webogram has nothing to do with that.
