### ISSUE TITLE
trying to delete telegram   

### ISSUE THREAD

**Issue by bpack12** [zhukov/webogram#1797]
my telegram was taken from me and im trying to delete it but i cant access account

**Comment by stek29** [comment]
contact support

**Comment by thecyberd3m0n** [comment]
Anuluj

16 sty 2019 04:28 "bpack12" <notifications@github.com> napisał(a):

I have summited tree tickets to support already almost 5 days ago

Sent from my iPhone

> On Jan 15, 2019, at 2:15 PM, Viktor Oreshkin <notifications@github.com>
wrote:
>
> contact support
>
> —
> You are receiving this because you authored the thread.

> Reply to this email directly, view it on GitHub, or mute the thread.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/zhukov/webogram/issues/1797#issuecomment-454638611>,
or mute
the thread
