### ISSUE TITLE
no timer for sms code after sending to app on other device

### ISSUE THREAD

**Issue by ilyapashuk** [zhukov/webogram#2091]
when I try to log in, I get message about code sent to telegram app on my other device.

but nothing about sms code

**Comment by YosefSinger** [comment]
Seems (to me) that this is a new policy of the server to block the sms confirmation option from all the telegram web clients (web.telegram.org, webk.telegram.org, webz.telegram.org and evgeny.nadymov.github.io). The desktop client also is the same story.

(Even forked versions of web.telegram.org made a while back are having the same issue, where such forked eatly versions were working fine until now!)

The only way that works is to log in with the iOS or Android app. Or have a logged in device so the confirmation code can be retrieved from there!

**Comment by ilyapashuk** [comment]
do you know any working feedback channels to official telegram developers

**Comment by Aokromes** [comment]
this issue belongs to https://bugs.telegram.org

**Comment by baptx** [comment]
@YosefSinger @ilyapashuk it is possible to receive an SMS code using a third-party desktop app like Kotatogram, mentioned here by @Aokromes: https://github.com/telegramdesktop/tdesktop/issues/16153

Here is the issue to upvote: https://bugs.telegram.org/c/4239
Other related issue to upvote: https://bugs.telegram.org/c/858

I noticed that logging in using an SMS code gives access to all encrypted messages, which is a very weak security used by Telegram since SMS codes can be intercepted (it looks like Telegram messages are saved on the server unlike WhatsApp).

**Comment by ilyapashuk** [comment]
yes, your messages are saved on the server, that's why you are able to view them from multiple devices, but secret chats, which you can create on your phone, are visible only on that phone and e2e encrypted. also you can setup 2 factor authentication in your account settings, and sniffed sms code will be not enough to login to your account.

**Comment by baptx** [comment]
@ilyapashuk thanks I thought Telegram messages were encrypted by default but apparently it is not the case unless for secret chats. I don't use Android / iOS on my smartphone and prefer to use the web version so I cannot use secret chats.
