### ISSUE TITLE
Option to hide avatars from contact/chat windows

### ISSUE THREAD

**Issue by igorsantos07** [zhukov/webogram#271]
Some users (like a friend of mine that does not have a GH account to report this by himself) prefer text-only contact lists. I remember seeing this type of option in several messengers that actually had user options (not like FB chat for example).

Would it be feasible to implement this? Would clean up the UI in the contact list when several of your contacts does not have pictures, or you just prefer to find them by name.

**Comment by zhukov** [comment]
This can be done with custom CSS, but for now we don't want so much settings in UI. And you can resize the browser window to enable mobile view - this can partially solve the problem.

**Comment by rodneyrod** [comment]
@zhukov Any chance on some advice on what needs to be changed in the CSS to bring this across?

Also, what would it take to disable all other forms of media besides text and profile pictures e.g. in line images, stickers, animations etc.

**Comment by Ryuno-Ki** [comment]
If you "solve" it via CSS, the requests to fetch the images are done nontheless. You just hide them with `display: none;`.

**Comment by rodneyrod** [comment]
@Ryuno-Ki Thanks for that, do you know what CSS classes would need to be changed to apply this to all in-line images?

**Comment by stek29** [comment]
@rodneyrod use DevTools, Luke.

**Comment by Ryuno-Ki** [comment]
@rodneyrod Since the app seem to use Twitter Bootstrap, you could use [https://github.com/zhukov/webogram/blob/82aec7a6daea93631b9eb14a89248d2b9580a906/app/vendor/bootstrap/css/bootstrap.css#L5325](hide). Be aware that it may distort the layout (because the avatar would be taken out of calculation of the layout).

In this case you could either go for `opacity: 0;` or for `visually: hidden;`.
