### ISSUE TITLE
[Suggestion] Ability to switch between different chats using Ctrl+Tab and Ctrl+Shift+Tab.

### ISSUE THREAD

**Issue by maisammusthafa** [zhukov/webogram#496]
Please add a feature that enables switching between chats using Ctrl+Tab and Ctrl+Shift+Tab. This feature exists in Telegram Desktop version, and it would be nice to have it in Webogram as well. Thanks.

**Comment by Akronix** [comment]
Hi zhukov!
I did not know this shortcuts, they are really handy, Thank you!!. I have some suggestion for them:

1. Firstly, I think a keyboard shortcuts summary or cheatsheet should be visible or easily accessible for any user. It took me quite a while to find these shortcuts when I was looking for the one to switch between conversations. I don't think I am very clumsy and I guess many people have the same problem or maybe they don't use it just because they don't even know that they exist.

2. A direct switching to any conversation would be a good idea.  I mean something like alt + shift + #. Where # is the number of that conversation starting from the top in ascending order.

3. Facebook chat shortcuts are, basically, <kbd>tab</kbd> for switching to next conversation and <kbd>shift</kbd> + <kbd>tab</kbd>. That confuses me pretty often, would be any chance to use these in this purpose too?? I know that telegram desktop don't match with this and that we would have to look for another shortcut to set focus to message/search fields.
I could help on this.

**Comment by Ryuno-Ki** [comment]
@zhukov Common UX pattern is to show shortcuts on <kbd>?</kbd>. Maybe you can add that one, too ;-)
