### ISSUE TITLE
Webogram blocked at work

### ISSUE THREAD

**Issue by zeldomar** [zhukov/webogram#615]
Hi,

My employer recently added webogram to the black list of the firewall: I obtain now the message "Access Denied 'Suspicious'" when I try to access the address "http://149.154.167.91/apiw1"

Is there a means to by-pass it please?

Thanks and regards

**Comment by alex-mayorga** [comment]
@zhukov Would you consider re-opening this?

The corporate proxy I'm jailed behind is now blocking Telegram it seems and even with https://zhukov.github.io/webogram/#/im I get this problem:

POST 
https://aurora.web.telegram.org/apiw1 [HTTP/1.1 403 Forbidden 3ms]

Is there a way around or shall I host my own server?

**Comment by anawim** [comment]
I'm also very interested in a way to make any version of Telegram work behind company proxy/firewall

**Comment by bb010g** [comment]
If you all haven't tried this already, talk to your IT dept. and see if they'll open it *first*. IT tends to not like people sneaking around firewalls. :)

**Comment by mindrunner** [comment]
I have a similar problem, which is kind of weird. Sorry for coming back to this, but I am actually more interested in understanding whats happening here than in cheating my employer. My setting is the following: Web is only accessible through a http proxy from our company or when connected to the company's VPN. Furthermore, there is tons of blocked sites, such as everything like video streaming, messaging, and so on. Thus, Telegram-Web is blocked. Unblocking is basically not a big deal. Using a Socks 5 SSH tunnel and a proxy browser plugin can make the whole internet visible while at work. Well, except one thing: Telegram.... When I try to log in, it is stuck on the "Generating Keys" part. When already logged in, it cannot load the message history and so on. Investigating further shows that all requests to 'https://vesta.web.telegram.org/apiw1' are timing out. What is going on here? Why is this one not going through my tunnel? What are these calls for? Any kind of hint is appreciated! :)

**Comment by tecknojock** [comment]
Alright, so I was dealing with this myself recently and figured I'd post a solution to this for yall.
So assuming you have a private server of your own, you need to alter this file:
https://github.com/zhukov/webogram/blob/40a8877953dbf6e0240efe45bac2c1bf8246735e/app/js/lib/mtproto.js, specifically 

`    var dcOptions = Config.Modes.test
      ? [
        {id: 1, host: **'[yourserver]/DC1',**  port: 80},
        {id: 2, host: '**[yourserver]/DC2'**,  port: 80},
        {id: 3, host: **'[yourserver]/DC3'**, port: 80}
      ]
      : [
        {id: 1, host: **'[yourserver]/DC4',**  port: 80},
        {id: 2, host: **'[yourserver]/DC5',**  port: 80},
        {id: 3, host: **'[yourserver]/DC6',** port: 80},
        {id: 4, host: **'[yourserver]/DC7',**  port: 80},
        {id: 5, host: **'[yourserver]/DC8',**   port: 80}
      ]

    var chosenServers = {}

    function chooseServer (dcID, upload) {
      if (chosenServers[dcID] === undefined) {
        var chosenServer = false,
          i, dcOption

        if (Config.Modes.ssl || !Config.Modes.http) {
          var subdomain = sslSubdomains[dcID - 1] + (upload ? '-1' : '')
          var path = Config.Modes.test ? 'apiw_test1' : **'apiw1/'**
          chosenServer = **'https://[yourserver]/' + subdomain + path**
          return chosenServer
        }

        for (i = 0; i < dcOptions.length; i++) {
          dcOption = dcOptions[i]
          if (dcOption.id == dcID) {
            chosenServer = **'https://' + dcOption.host + '/apiw1'**
            break
          }
}`

And then edit your Nginx config file to include the following locations:
`location ^~ /pluto/apiw1/ {
            proxy_pass https://pluto.web.telegram.org/apiw1/;
}
location ^~ /venus/apiw1/  {
            proxy_pass https://venus.web.telegram.org/apiw1/;
}
location ^~ /aurora/apiw1/ {
            proxy_pass https://aurora.web.telegram.org/apiw1/;
}
location ^~ /vesta/apiw1/ {
            proxy_pass https://vesta.web.telegram.org/apiw1/;
}
location ^~ /flora/apiw1/ {
            proxy_pass https://flora.web.telegram.org/apiw1/;
}
location ^~ /pluto-1/apiw1/ {
            proxy_pass https://pluto-1.web.telegram.org/apiw1/;
}
location ^~ /venus-1/apiw1/  {
            proxy_pass https://venus-1.web.telegram.org/apiw1/;
}
location ^~ /aurora-1/apiw1/ {
            proxy_pass https://aurora-1.web.telegram.org/apiw1/;
}
location ^~ /vesta-1/apiw1/ {
            proxy_pass https://vesta-1.web.telegram.org/apiw1/;
}
location ^~ /flora-1/apiw1/ {
            proxy_pass https://flora-1.web.telegram.org/apiw1/;
}
location ^~ /DC1/ {
            proxy_pass http://149.154.175.10:80/;
}
location ^~ /DC2/ {
            proxy_pass http://149.154.167.40:80/;
}
location ^~ /DC3/ {
            proxy_pass http://149.154.175.117:80/;
}
location ^~ /DC4/ {
            proxy_pass http://149.154.175.50:80/;
}
location ^~ /DC5/ {
            proxy_pass http://149.154.167.51:80/;
}
location ^~ /DC6/ {
            proxy_pass http://149.154.175.100:80/;
}
location ^~ /DC7/ {
            proxy_pass http://149.154.167.91:80/;
}
location ^~ /DC8/ {
            proxy_pass http://149.154.171.5:80/;
}`

And that ought to allow you to proxy all the telegram requests. Maybe @zhukov will be willing to allow us to override defaults with a config file so that its easier to stay up to date.

**Comment by mindrunner** [comment]
What exactly is happening there? Shouldn't all traffic automatically go through the configured SOCKS connection? Why do we need an additional Proxy/Webserver?

**Comment by tecknojock** [comment]
Sure, if you wanna run it through a SOCKS that should work fine. But I think you'll find employers will find a socks connection suspicious while less so since it looks more like normal traffic. 

As far as what's going on, you're using your web server to mitm your own connections and pass them on to the telegram servers

**Comment by mindrunner** [comment]
@tecknojock But it does not. See my comment from Feb 2 2016.

**Comment by tecknojock** [comment]
Oh right! In that case I dont really know.
