### ISSUE TITLE
AppCache is outdated [Firefox]

### ISSUE THREAD

**Issue by aaruni96** [zhukov/webogram#638]
Communicating with stickers on mobile devices renders the webogram useless.
![screenshot from 2015-01-04 13 43 03](https://cloud.githubusercontent.com/assets/7453256/5605260/a2c9b2e0-9417-11e4-85c0-10519d02f951.png)

**Comment by zhukov** [comment]
What do you mean?
BTW, the screenshot is of outdated version of app.

**Comment by aaruni96** [comment]
Telegram on my android looks like this : 
![2015-01-04](https://cloud.githubusercontent.com/assets/7453256/5605295/39000c9a-9419-11e4-9a7c-9ad39ebfa595.jpg)


But ever since I started using stickers, webogram is completely empty.

Also, its on web.telegram.org. I can't do anything about the version over there.

**Comment by zhukov** [comment]
What is the browser? Try cleaning all the browser cache to force app update.
On Chrome / Chromium you can open this url chrome://appcache-internals/ to clean webogram cache manually.

**Comment by aaruni96** [comment]
Its firefox.

**Comment by aaruni96** [comment]
Cleared cache. App is still 0.3.6, and webogram screen is still emtpy.

**Comment by yagop** [comment]
Same problem here:
```
"Error: length method called on incompatible Object
a@https://web.telegram.org/js/app.js:6:24331
o@https://web.telegram.org/js/app.js:6:24589
L@https://web.telegram.org/js/app.js:6:26720
L@https://web.telegram.org/js/app.js:6:27087
L@https://web.telegram.org/js/app.js:6:26791
L@https://web.telegram.org/js/app.js:6:27087
L@https://web.telegram.org/js/app.js:6:26791
L@https://web.telegram.org/js/app.js:6:27087
R@https://web.telegram.org/js/app.js:16:2723
p/</<@https://web.telegram.org/js/app.js:17:12864
o@https://web.telegram.org/js/app.js:6:24660
p/<@https://web.telegram.org/js/app.js:17:12805
l@https://web.telegram.org/js/app.js:8:16426
c/<@https://web.telegram.org/js/app.js:8:16598
Hn/this.$get</u.prototype.$eval@https://web.telegram.org/js/app.js:8:23791
Hn/this.$get</u.prototype.$digest@https://web.telegram.org/js/app.js:8:22283
Hn/this.$get</u.prototype.$evalAsync/<@https://web.telegram.org/js/app.js:8:23878
r@https://web.telegram.org/js/app.js:7:10671
jt/p.defer/n<@https://web.telegram.org/js/app.js:7:12671
n@https://web.telegram.org/js/app.js:2:10700
"
```

**Comment by zhukov** [comment]
Strange issue with appcache. Can anyone contact me at telegram.me/izhukov ?

**Comment by marlosirapuan** [comment]
Chrome here. No problem.

**Comment by Yajo** [comment]
Firefox here. No problem too (except for https://github.com/zhukov/webogram/issues/640).

**Comment by malishev** [comment]
@aaruni96, @yagop try also [clearing offline website data](https://support.mozilla.org/en-US/kb/delete-browsing-search-download-history-firefox?redirectlocale=en-US&redirectslug=Clear+Recent+History#w_how-do-i-clear-my-history)

**Comment by pchinea** [comment]
It's a problem with appcache, to solve it, press shift + F2 and type: "appcache clear" (without quotes), then reload.

**Comment by rmed** [comment]
On Firefox OS with webogram 0.3.6 (current version in marketplace), conversations that include stickers either show messages in a weird order (last message followed by messages from a couple of days ago) or show no messages at all. Given that most people are trying out the new stickers, it's nearly impossible to use the app on FFOS.

**Comment by Yajo** [comment]
In another computer I had to do the `appcache clear` trick in web.telegram.org. The FF marketplace app in FF desktop fails as @rmed said. Is it possible (and useful) to execute `appcache clear` in the unhosted app?

**Comment by nukeador** [comment]
Cleaning the app cache I get the latest version.

Checking https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache#The_cache_manifest_file

I see that there are some entries in the app manifest I don't know the reason:

https://web.telegram.org/webogram.appcache

> NETWORK:
> http://*
> https://*
> *

Why these wildcards?

Also I would change the version number first comment to something more simple (just in case)

``# v1 - 2011-08-13``

**Comment by nukeador** [comment]
BTW, the stickers support in Firefox is #636

**Comment by zhukov** [comment]
@nukeador 

```
http://*
https://*
```

Are needed for XHR requests to Telegram API to bypass cache checks and always perform online.

The last one `*` is probably for other protocols like "blob:", "filesystem:" etc. Not sure if we need it, but I don't think it can cause any problems with manifest.

**Comment by nukeador** [comment]
@zhukov why not including the wildcards with the Telegram API URLs instead of any URL? Just in case.

I just did a quick read through the docs and try to figure out what's is different or can cause a conflict.

**Comment by zhukov** [comment]
We also have google maps preview and some other ajax requests. I don't see why we should use white list instead of black list for this purpose. We want only use cache for page and depending assets (which are already in CACHE section).

I've also did some research with guys who had this bug reproduced. It looks totally like some problem in Firefox. The manifest was updated on server-side with all the headers correctly set, but during appcache update Firefox saw only outdated version of manifest. While we had no problems like this in Chrome and Safari.

**Comment by Yajo** [comment]
@zhukov Then maybe you should just file it in https://bugzilla.mozilla.org/

**Comment by nukeador** [comment]
@zhukov I can open a bug for you if you get me the steps to reproduce the problem.

**Comment by zhukov** [comment]
The problem is that I can't reproduce this on my PCs. I'm going to see the first browser with the bug today, may be will get enough info.

**Comment by zhukov** [comment]
I think, I've found one issue, at least. It may be is not connected to the original problem and be the issue of manifest validation tool, but we can't be sure, it's better to check, may be it's all connected.

When I open the up-to-date version of the app in Firefox and try to validate the manifest, with Shift + F2 and then `appcache validate`, I've got an error, because the file manifest file `webpgram.appcache` in

```html
<!doctype html><html lang=en manifest=webogram.appcache ng-csp 
```

did resolve to https://web.telegram.org/#/webogram.appcache instead of https://web.telegram.org/webogram.appcache, which is an index.html link.

I also tried to replace `webogram.appcache` with `./webogram.appcache` or `/dist/webogram.appcache` etc, that didn't work.

It seems like some hash navigation problem.

![screen shot 2015-01-19 at 13 37 08](https://cloud.githubusercontent.com/assets/775173/5799184/6ba767d8-9fe0-11e4-8eb3-820c3e5451f9.png)

![screen shot 2015-01-19 at 13 38 39](https://cloud.githubusercontent.com/assets/775173/5799189/85dc7440-9fe0-11e4-9d22-8ed9fd4602f2.png)

Steps to reproduce:

1. Open https://web.telegram.org/#/login or https://web.telegram.org/#/im (if authorized)
2. Shift + F2 to enable console
3. Type `appcache validate`

**Comment by nukeador** [comment]
@zhukov have you tried to specify the full absolute URL for the manifest file instead of the relative path?

**Comment by zhukov** [comment]
No, I didn't try, I guess this will work. But this will make the app domain-dependent, I don't like the idea.

**Comment by nukeador** [comment]
Or maybe make the urls not to use /#/ and use just # and you will avoid problems with relative urls adding /#/.

Alternatively maybe you can make https://web.telegram.org/#/webogram.appcache to load the webogram.appcache file instead of a redirect to /#im/

**Comment by Yajo** [comment]
Maybe it's AngularJS... Have you tried setting the ng-app in <body> instead of <html>?

**Comment by zhukov** [comment]
I think, it's a bad idea to change navigation style in app due to such bug. Most of AngularJS apps have same routing schema by default. 

At first we should understand, if this is a Firefox appcache bug, or dev console bug. Or may be it's a feature.

**Comment by nukeador** [comment]
I guess it's the correct behavior when checking the relative path.

If the relative path is ``webogram.appcache`` and the current url is ``https://web.telegram.org/#/im`` then the path to look is:

``https://web.telegram.org/#/webogram.appcache``

**Comment by zhukov** [comment]
I don't think so. Hash part is always treated as something separate from resources paths.

**Comment by nukeador** [comment]
@zhukov even if it has a ``/`` at the end?

I think ``https://web.telegram.org/#/im`` is not the same as ``https://web.telegram.org/#im``.

Is there a way to test urls without the ``/`` at the end to see if the path is now correct?

**Comment by stripTM** [comment]
Try validate with http://manifest-validator.com/ and I get:

Line 89: Invalid resource identifier.
http://*
Line 90: Invalid resource identifier.
https://*
Line 91: Error parsing resource 

You can try to change it as in the example of w3c (*)
NETWORK:
*
(*) http://www.w3.org/html/wg/drafts/html/CR/browsers.html#offline

**Comment by MDesigner** [comment]
how to use telegram web in my web page by iframe ?

**Comment by NekR** [comment]
This is Firefox's bug where it doesn't load fresh files, so app is stuck with stale version. This could be fixed by generating unique names on each build or not using AppCache in Firefox.

Also, it won't be fixed in Firefox everyone supposed to use ServiceWorker in newer versions of browsers. So I strongly recommend that.

**Comment by zhukov** [comment]
We now have support for service workers, this is not actual anymore.
