### ISSUE TITLE
Sign in, try remove code and select country

### ISSUE THREAD

**Issue by ArtemFitiskin** [zhukov/webogram#650]
* Open login page
* Select country
* Delete the code
* Re-select country

![screen](https://cloud.githubusercontent.com/assets/5507542/5699948/f1c0d242-9a44-11e4-9318-51ca84ff15d4.png)

**Comment by zhukov** [comment]
If you really want to make PR, I would recommend using more generic approach. Naming event 'country_selected' in shared directive is not a good thing to do.

First I would suggest to try adding 'change' event here: https://github.com/zhukov/webogram/blob/master/app/js/directives.js#L2528

If that doesn't help, you can create a separate scope event 'value_updated' (instead of 'country_selected ') and broadcast it from controller.

**Comment by ArtemFitiskin** [comment]
> First I would suggest to try adding 'change' event here:
> https://github.com/zhukov/webogram/blob/master/app/js/directives.js#L2528

It was my first idea, but it doesn't work.

Please check updated PR. It's OK?
