### ISSUE TITLE
Add notifyAboutMessage on startup

### ISSUE THREAD

**Issue by TitanNano** [zhukov/webogram#655]
Hello,
So simple push is still not working as it should and I finally was able to find the problem. 
my test case:
close the app -> send a message from a different device to your account -> go into the task manager of your device -> telegram appears and you're able to see how it loads -> the app screenshot in the taskmanager shows a new message, but you won't get a notification -> send an other message to your device -> the app is still running and triggers a notification.

Based on this test result I assume that the app doesn't display notifications if there are new messages at the app start. This should be changed and I think then the simple push mechanism will finally work properly.

**Comment by zhukov** [comment]
>if there are new messages at the app start
What does it mean?

**Comment by TitanNano** [comment]
>>if there are new messages at the app start

> What does it mean?

that there are new messages which weren't there before the app got quit. Basically new unread messages.

**Comment by zhukov** [comment]
Did you kill the app before push arrived? Does FxOS store its previous state?

**Comment by TitanNano** [comment]
yes I killed it and no every app gets reloaded when it gets restarted.

2015-01-19 11:32 GMT+01:00 Igor Zhukov <notifications@github.com>:

**Comment by TitanNano** [comment]
I personally suggest to keep track of for which messages a notification has been triggered so we know at the application launch if we need to trigger some for the current unread messages.

**Comment by stephenjudge** [comment]
Does my issue explanation at https://github.com/zhukov/webogram/issues/667 make sense to you, and would it be useful to repost it here, or is the reference to it enough. I don't quit understand TitanNano's explanation but that is likely because I don't know how Telegram is using FxOS's push notifications, or if it is at all.

**Comment by TitanNano** [comment]
@stephenjudge I understood it and I think @zhukov did so too. The thing is that you just described the symptoms reflecting in the user experience. The actual problem lies in the technique how Webogram works. If you're interested I can explain it to you in more detail.

**Comment by stephenjudge** [comment]
@TitanNano Good, thanks for the offer, you don't need to though. I can't contribute to the code and I am primarily interested in making sure you understand the problem from a user experience. I am keen to see to see this fixed. 

The FxOS device I am referring to is a phone I bought for my mother. Her first ever smart phone. I bought it because I felt it was a simple smartphone to understand as a beginner compared to the settings and gestures of an Android for a person coming from an old button phone. Telegram is the only secure private chat platform available to her. I'm aware WhatsApp has now implemented the TextSecure protocol and there is an unofficial FxOS WhatsApp client, but I just still don't trust a completely closed platform like WhatsApp. The rest of us in the family are using Androids. It is important that we can message her as easily as we can send her an SMS. So it is a bit confusing and annoying for her that notifications don't work. I have to nag her to remember to launch Telegram as soon as she turns on her phone or she won't see our messages.

Also given that FxOS devices are targeted at markets and users were this will also be their first smartphone, it is important for chat apps like Telegram that these things work or users will drop them in favour of the other existing or future FxOS chat apps like OpenWapp (WhatsApp client) or LINE.

Thanks for working on this bug.

**Comment by TitanNano** [comment]
@stephenjudge okay I see. 
Just to mention that I'm working on the Loqui project my self (the other nonofficial WhatsApp client) and 'cause the backend all these clients use does not implement textsecure jet, you couldn't even talk to the 
FxOS device from and Android WhatsApp client. 

I also have a work around for this bug which might help you. If Telegram isn't running on the device you'd like to message to: Send one message, wait for a couple of seconds and then send an other message, now your chat partner should see a notification for your second message. I hope this helps, I'm doing it like this at the moment.

**Comment by stephenjudge** [comment]
@TitanNano Good luck with your Loqui project. I do commend WhatsApp for implementing the TextSecure protocol, but I probably will never trust WhatsApp completely until they open all their code which is never going to happen.

If a messenger is open source and using a recognised secure messaging protocol then I am likely to trust it, or at least trust it more than the likes of WhatsApp, Viber, LINE or Skype etc. At the moment the only apps I trust the most are TextSure, Telegram, Kontalk, Surespot and maybe Heml.is when it is released. Even Telegram I am a bit unsure of because they are using an untested new protocol of their own which makes me nervous. I personally prefer to use TextSecure because the reliability on the security of their protocol and the fact it can encrypt SMS. But then I have had problems using with others who just can't get their head around how it works, switching from Encrypted to Unencrypted SMS and Push Messaging. Telegram is more user friendly in this regard and has other nice feature such and multi platform and multi OS clients that TextSecure does not have yet.

Anyway, I am just grateful there is some secure messaging app on FxOS I can use with my mother. I would hate to have to start using WhatsApp or LINE with her. I'd probably just stick with SMS/MMS in that case. I will try your suggested work around when I am in person with my mother and I can see it work in action. Thanks for tip anyway.

**Comment by zhukov** [comment]
@TitanNano @stephenjudge thanks for detailed description of the problem.

I think, I'found some way to implement the solution. Hope to fix this soon.

**Comment by zhukov** [comment]
Added some code modifications to notify about unread messages since last app opening. Hope this will help, but need to test.

**Comment by TitanNano** [comment]
Okay, thank you. I'll do some testing :)

**Comment by stephenjudge** [comment]
I wonder could this Mozilla Hacks blog post about Firefox OS Add-ons and tutorial to build an Unread Notifications add-on be relevant here https://hacks.mozilla.org/2015/11/building-an-ios-style-unread-notifications-add-on-for-firefox-os/
