### ISSUE TITLE
Support for Firefox Social API

### ISSUE THREAD

**Issue by pahnin** [zhukov/webogram#669]
Is there any plan to support/extend to Firefox Social API?
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Social_API
Firefox Social API can provide easy access to webogram even when the tab is closed.
I think for any mutual users of Firefox and Telegram this would be of major importance, ability to share articles with single clicks, Ability to run webogram in background. It would be awesome. Has there been any thoughts about this before?

**Comment by zhukov** [comment]
I don't like spending much time on non-universal solution. As far as I can see, this is only supported on Firefox, not Chrome, Safari and Opera.

**Comment by Akronix** [comment]
I just want to say, I'd really like to have this feature in webgram.
I don't know how hard it's to get it down though.

**Comment by fhoshino** [comment]
This would make webogram much handy on firefox.
Looking forward if it happens.

**Comment by sabret00the** [comment]
I'd really love this. The Social API that Firefox use is open source and so anyone could create an extension for the other browsers to utilise it. It seems a no-brainer when you consider that WhatsApp have buttons on most major news sites now when accessed via mobile, such a move by Telegram would go a long way to rebalancing the scales in an open and progressive manner.

**Comment by Akronix** [comment]
I'm willing to try to implement this, although some points have to be met first:
1. @zhukov is ok with merging it.
2. I would start to work on it from 20th of June, right now I have no any time.
3. It's not too tricky.

**Comment by zhukov** [comment]
@Akronix sure, take a try

**Comment by sabret00the** [comment]
Did you have any success @Akronix ?

**Comment by Akronix** [comment]
I actually didn't try :disappointed: I'm sorry.
Nevertheless, I had taken a look to the Social API and I think it could be made.
I'll take this as a personal assignment. Let me try this out for one week and I'll let you know the results.

**Comment by sabret00the** [comment]
I'll keep an eye out for your progress.

**Comment by Ryuno-Ki** [comment]
@Akronix The week is over *hint*

**Comment by Akronix** [comment]
Hi folks!
Sorry, for replying a bit later.
I had to host the webapp in a service supporting SSL since Firefox only allows you to add Social providers if they are SSL-secured (This, btw, slow me down a lot my work because this is not documented anywhere and then I had to set up a development solution so that Firefox would accept it)

Either way, I've come up with something semi-functional for the share panel...It still needs some work though via a dedicated share.html page and clean the code quite a bit.

Here it is:
https://akronix-webogram.herokuapp.com/app/index.html
You just have to press on the Telegram dropdown menu and press on the button reading "Activate". Then, enable the service and use through the Firefox' share button.


Of course, we could add more capabilities within the Mozilla's Social API possibilities.

If we want to be exposed to the Firefox userbase and being distributed directly in Firefox, so that we can get rid of any button on the interface to activate the service; webogram has to meet with a [certain criteria] (https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Social_API/Criteria) and pass a review.

**Comment by sabret00the** [comment]
You're brilliant @Akronix . You should submit a pull request so @zhukov can get this accepted by Firefox. It'll be a huge boon for both Firefox and Telegram.

**Comment by nos1609** [comment]
@Akronix any updates? Tested and it already has the necessary functionnality. web.telegra.org is already https enabled, so conform to any mozilla criterea. Can you create a pull request, please?

**Comment by Akronix** [comment]
Ok, I'll review it and try to open a pull request along this weekend.

**Comment by sabret00the** [comment]
@Akronix Did you get round to opening a pull request for this?

**Comment by marsjaninzmarsa** [comment]
Depreciated, removed from Fx, should be closed.

**Comment by Akronix** [comment]
> Depreciated, removed from Fx, should be closed.

sadly true. @pahnin @zhukov
