### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by alex-mayorga** [zhukov/webogram#673]
When loading https://zhukov.github.io/webogram/#/im I get this error on Nightly's "Browser Console":

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://aurora.web.telegram.org/apiw1. This can be fixed by moving the resource to the same domain or enabling CORS.

**Comment by Walkman100** [comment]
Not sure if this will fix it, but you should be using https://web.telegram.org anyway.

**Comment by alex-mayorga** [comment]
Can't due to issue #615 =(

**Comment by zhukov** [comment]
This is due to Telegram is blocked at your network. When your proxy server intercepts server response and places some blocking page instead of it, CORS headers are also removed. So you see this error.

Did Webogram show you a friendly alert about netork problems or "Connecting..." in the head (if already logined) ?

**Comment by zhukov** [comment]
Btw, try opening https://aurora.web.telegram.org/apiw1 in usual browser window, when the problem happens. Send here a screenshot of the page you see.

**Comment by alex-mayorga** [comment]
@zhukov,

This is what the header at https://zhukov.github.io/webogram/#/im looks like:
![673-2](https://cloud.githubusercontent.com/assets/649262/6005039/ed9b9b64-aacc-11e4-9f36-2194170b4c26.PNG)

This is what loading https://aurora.web.telegram.org/apiw1 shows:
![673](https://cloud.githubusercontent.com/assets/649262/6005042/f04ba70a-aacc-11e4-9b3d-49968486db0b.PNG)

**Comment by zhukov** [comment]
Yeah, that's definitely not a problem of Webogram. Closing the issue.

As for the blocking itself, I don't think I can help you with workaround. There are a lot of articles about VPNs, TOR and proxies on the internet. Telegram can't solve this from its side: system administrators can easily add any new IP address / DNS hostname to the black list. So you should either ask them to remove it, since you need Telegram for work, or manage to bypass the blocking by yourself.
