### ISSUE TITLE
Bad regex in url (unrelated to security)

### ISSUE THREAD

**Issue by revskills** [zhukov/webogram#692]
Please test to share a url finished in /index.html /index.php /whatever.ext. The link remove the .ext part so the URL link feature is completely broken.

**Comment by revskills** [comment]
The new update works, however you can link to index.html only mentioning the file. So I'm not sure if this is a normal feature.

**Comment by zhukov** [comment]
Duplicate #690

**Comment by zhukov** [comment]
>you can link to index.html only mentioning the file.
what do you mean?

**Comment by revskills** [comment]
write in a chat directly without host/protocol 'index.html' or 'file.extension'

**Comment by zhukov** [comment]
yep, that's because we don't check top level domains for now.

@ArtemFitiskin, I've also faced some bad samples, like: API.messages.readHistory  etc. I think, that a good idea might be to check the domain name with TLD list and wrap link if the domain is known. Otherwise wrap it only if the url has protocol.

**Comment by ArtemFitiskin** [comment]
@zhukov Great idea. I've already fixed it and can create the PR. Also, just now I am trying to resolve bug with end brackets.
