### ISSUE TITLE
Url and Emoji

### ISSUE THREAD

**Issue by pgrimaud** [zhukov/webogram#702]
There's a little issue with an url containing an emoji.

Example : 
string(dot)string appears as http://string.string.

With an emoji : 
string(dot)emoji appears as http://string.��

Maybe, do not replace with an url when an emoji is present or encode it.

Thanks

**Comment by zhukov** [comment]
It's because of encodeEntities here https://github.com/zhukov/webogram/blob/master/app/js/services.js#L3681

/cc @ArtemFitiskin :smile: I know it's not related to your PR, but may be you have an idea, how we can escape emoticons in order to make it work correctly, since you have got so deep into the code.

**Comment by IPRIT** [comment]
I can suggest to search in the found "match[4]" part of Emoji. This element is responsible for URL & e-mail. If there is one, then we insert Emojies. If you don't find the smile, then insert match[4] as a href link. My solution here: https://gist.github.com/IPRIT/c3b4295453ee8ed3abcd

The code above starts with this line 3641 in services.js https://github.com/zhukov/webogram/blob/master/app/js/services.js#L3641

![Best example forever](http://s.twosphere.ru/screenshots/01_55_30.png)

**Comment by IPRIT** [comment]
However you also need to change the preview message ![best example too](http://s.twosphere.ru/screenshots/01_59_52.png)

**Comment by ArtemFitiskin** [comment]
@IPRIT your gist looks good, but I found a problem with links like:

``http://foo.com/unicode_(✪)_in_parens``

* exist
![exist](https://cloud.githubusercontent.com/assets/5507542/6224386/267f3d80-b68c-11e4-86ff-0ce5cb4db43d.png)

* gist
![gist](https://cloud.githubusercontent.com/assets/5507542/6224390/31f05244-b68c-11e4-9fdc-709f31ea685e.png)


Totally was crashed.

**Comment by ArtemFitiskin** [comment]
Maybe limit verification enough for two cases: 
1) emoji at the end of the URL, then it must be separated, as we did with brackets; 
2) smiley at the TLD place and in such cases, even if a protocol, unset the link.

**Comment by zhukov** [comment]
GitHub: http://google.com/🎉?q=😀

First of all, I think we need to fix the broken URL inside href. When we paste the same `http://google.com/?q=😀` in Webogram, the link is broken. I guess, we could urlencode the path + query parts (the only ones, which allow unicode).
As for the text inside `<a>...</a>`, it is less important. In order to replace emojis inside the link, we'll need to create another one regex and match every link.

**Comment by IPRIT** [comment]
@zhukov, as I understand you want to encode the text and put it in the href and content <a></a> first replace Emoji, and then insert?
