### ISSUE TITLE
[Feature Request] Keyboard shortcut for LRU chat

### ISSUE THREAD

**Issue by mishra69** [zhukov/webogram#757]
Currently the chat list is sorted by which one has received the most recent message. 

There should be a way to access the least recently used chat (used by me). A keyboard shortcut will be great.

**Comment by profilink** [comment]
Если возможно, Игорь, бросьте пожалуйста ссылку для загрузки не офф. русифицированной версии Telegram для Android, 2.3.5 и 4+ версий. Буду искренне благодарен, т.к. хотел бы пользоваться но многие моменты в интерфейсе приложения, не ясны не только мне к сожалению.

If possible, Igor, please drop a link to download is not off. Russian version Telegram for Android, 2.3.5 and 4+ versions. I would be very grateful, because I would like to use but many times in the application interface are not clear not only to me unfortunately.

**Comment by zhukov** [comment]
@mishra69 what for? You can scroll all the way down to needed chat.

**Comment by mishra69** [comment]
In a scenario where I am chatting with two people, the chat list is sorted by who sent the most recent message. When I want to switch between chats, I have to look at the list and make a decision every time. I need a way (a keyboard shortcut) which can do the switching deterministically. Something like the Alt+Tab on windows.

**Comment by mishra69** [comment]
I think LRU isn't the right term for this. Most recently used ?

**Comment by zhukov** [comment]
I think that what you need is static order for the chats. This is the only way to have predictable positions of conversations.

**Comment by zhukov** [comment]
ah.. and btw, you can try using 'back' button in browser. this should return you back after you switched a conversation.

**Comment by zhukov** [comment]
@mishra69 Is #768 what you need?
