### ISSUE TITLE
Improve rendering in Firefox

### ISSUE THREAD

**Issue by VictorOsorioMedrano** [zhukov/webogram#759]
Bad rendering of Telegram Web in Firefox
Note: this not happen in Google Chrome

![render bad 1](https://cloud.githubusercontent.com/assets/8153074/7031186/54898f18-dd2f-11e4-9d93-523fb6229395.png)
![render bad 2](https://cloud.githubusercontent.com/assets/8153074/7031187/54953cfa-dd2f-11e4-8b11-92a4e17218cc.png)
![render bad 3](https://cloud.githubusercontent.com/assets/8153074/7031188/549e79aa-dd2f-11e4-8998-d21a36283eb4.png)

**Comment by zhukov** [comment]
Did you try running the app in clean profile? I guess the problem is with some of your extension or settings.

**Comment by VictorOsorioMedrano** [comment]
Yeah I try in incognito , but the same happen

**Comment by ArtemFitiskin** [comment]
Clean Firefox 29/35/37. That's all right.

**Comment by VictorOsorioMedrano** [comment]
I clean Firefox 37 and continue the same problem. Maybe it's a proble with my grapihc card

**Comment by zhukov** [comment]
Not sure, what can cause such rendering problems.
I see some skype icon  on the screenshot, which is added by some plugin. 

Not sure if incognito disables all the plugins.
I would advice to create a new clean profile in Firefox and try again. Here is the manual: https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles#w_creating-a-profile

Looking at the screenshots I don't think that these problems are possible to be caused by the app itself.

**Comment by Ryuno-Ki** [comment]
Be aware, that there are AddOns like [Switchy](http://143th.net/post/103628851986/switchy-0-9-released) which helps you manage profiles :)

**Comment by anewuser** [comment]
@VictorOsorioMedrano go to *about:preferences#advanced* and uncheck "Use hardware acceleration when available".

**Comment by VictorOsorioMedrano** [comment]
@anewuser Wow thanks for fix my problem really thanks. I hope @zhukov include a note in the app for this problem in Firefox

**Comment by anewuser** [comment]
@VictorOsorioMedrano Telegram has nothing to do with this. The problem is that Firefox doesn't play well with your graphics adapter and shouldn't be using it by default. You should report it to https://bugzilla.mozilla.org/ along with your hardware specs and screenshots..
