### ISSUE TITLE
show webpage attachements on mobile too

### ISSUE THREAD

**Issue by TitanNano** [zhukov/webogram#892]
It would be great if we could see the webpage attachments on mobile too, not only the sent URLs.

**Comment by berbaquero** [comment]
:+1:

**Comment by berbaquero** [comment]
Hmm, very good point, @Ryuno-Ki. I'd say it could be built into as a config option, then.

**Comment by TitanNano** [comment]
there is already an option to disable all previews on mobile....

**Comment by Ryuno-Ki** [comment]
Another argument: Privacy. If I want to see a preview, there needs to be a kind of API which the app can query (in order to fetch details). Or at least a GET request.

I can image, for a people with need for privacy (think minorities or journalists) this could be bad, since it would inform the web page hoster that there was a "visit" and could disclose the position via IP or so.

I can imagine, this is relevant in states like Russia ;-)

**Comment by marco-c** [comment]
The option to disable previews would support all these use cases.
