### ISSUE TITLE
Close/Hide current conversation button

### ISSUE THREAD

**Issue by fooness** [zhukov/webogram#893]
Unfortunately, there’s no button/link back to the webclients start/home page, https://web.telegram.org/#/im …

I think it would be good—because intuitive, we know from almost any website that clicking on the logo/header/banner brings us back to the start/home page—to separate the menu/burger icon, which opens the drop down menu, from the Telegram text, which could be a link to the start/home page.

Thanks!

PS: OSX 10.10.5, Chromium Version 46.0.2468.0 (64-bit)

<img width="1273" alt="screen shot 2015-09-03 at 12 02 16" src="https://cloud.githubusercontent.com/assets/11408027/9655806/0cfc1538-5234-11e5-9ea8-b5668d77a4d6.png">

**Comment by rockfield** [comment]
@fooness I didn't catch your idea :)
What functionality do you mean? What is "webclients start/home page" ? Do you mean action to close current conversation?
Because in Telegram as well as in other different chat clients you start using program with chatting. Main functionality is start point to use.

On your provided link/screenshot usually you will see previous conversations on left sidebar except you are a new user.

**Comment by fooness** [comment]
@rockfield

I kind of mean action to close the current conversation, yes. A link to the start page with no conversation selected, I meant. So that it looks like in the screenshots, just with the conversations on the left side …

**Comment by rockfield** [comment]
@foones
Maybe rename issue with the �Hide current conversation button� name? :)
Well, I don�t need this functionality but we need to wait other members' opinion or Igor Zhukov�s the one.

**Comment by fooness** [comment]
Good point, thanks.

**Comment by fooness** [comment]
@zhukov what do you think about it?

**Comment by zhukov** [comment]
For now there is no place in UI for it. You can use `Esc` button for this purpose.
