### ISSUE TITLE
Option to also ask password when opening web app

### ISSUE THREAD

**Issue by marcopaganini** [zhukov/webogram#987]
Right now, the "Two Step" option only asks for a password when logging in from a device without the login credentials. It would be useful to have an option to also ask for this password when the app is opened in the browser, even if the credential cookies are already in place. This would increase the privacy on shared computers and reduce the risk of someone seeing other people's conversations by opening the web app on computers left temporarily unattended.

**Comment by zhukov** [comment]
Sorry, I'm not going to implement this in nearest future. In order to make this truly secure, we need to encrypt every file stored in IndexedDB, which is difficult enough and will make app slower.

Feel free to fork the project and implement this yourself. I would also advise to use OS-provided lock screen after screen sleep or use  Telegram native desktop apps which provide this feature.
